### ISSUE TITLE
scons examples fails on osx

### ISSUE THREAD

**Issue by gaborpapp** [alex-berman/sonotopy#20]
/usr/local/include/sonotopy/SpectrumMapCircuit.hpp:35: error: type 'sonotopy::SpectrumMap' is not derived from type 'sonotopy::SpectrumMapCircuit'
/usr/local/include/sonotopy/SpectrumMapCircuit.hpp:35: error: expected ';' before '_' token
/usr/local/include/sonotopy/SpectrumMapCircuit.hpp:53: error: expected ';' before '_' token
/usr/local/include/sonotopy/SpectrumMapCircuit.hpp:54: error: expected ';' before '*' token

**Comment by alex-berman** [comment]
SpectrumMapCircuit.hpp has been removed. perhaps you need to delete old include files manually from the install directory? I think I needed to.

**Comment by gaborpapp** [comment]
thanks. <code>scons -c install</code> solved it.
