### ISSUE TITLE
Source `examples/ColoredGridMapDemo.cpp' not found

### ISSUE THREAD

**Issue by yangh** [alex-berman/sonotopy#25]
Hi Alex

I'm trying to build the latest code, and encountered this issue:

scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build/release/examples
g++ -o build/release/examples/Demo.o -c -Wall -pedantic -ffast-math -fPIC -g0 -O3 -pthread -Ibuild/release/examples/include -Iexamples/include -Iinclude/sonotopy -Ibuild/release/include examples/Demo.cpp
scons: *** [build/release/examples/ColoredGridMapDemo.o] Source `examples/ColoredGridMapDemo.cpp' not found, needed by target `build/release/examples/ColoredGridMapDemo.o'.
scons: building terminated because of errors.

Since: commit/63c6e3c721fb1
 added ColoredGridMapDemo, with sonotopic hue 

Thanks

**Comment by alex-berman** [comment]
Hi,
It seems that I forgot to add some files in the last commit (63c6e3c721fb1d2c8f267713c53c8dc35170887e). Since the commit isn't very important for the library as such, I suggest trying an earlier commit (e.g. 5486dae08bb704959477cdfe43e4b94a399b0d2c).

Hope it helps!

**Comment by yangh** [comment]
Hi Alex

Got it, Thanks.
